# Use root/mongoadmin as user/password credentials
version: '3.1'

volumes:
  data_db:

services:

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - ./data_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongodb://root:mongoadmin@mongo:27017/
    networks:
      - backend

  api:
    container_name: api-django
    restart: always
    build: ./
    working_dir: /ine_mongodb_api
    command: bash init.bash
    ports:
      - 8000:8000
    environment:
      MONGO_URI: mongodb://root:mongoadmin@mongo:27017/
    volumes:
      - .:/api
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge